name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm and cache dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.30.3
        env:
          CACHE_KEY: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm config set cache-dir ~/.pnpm-cache
          echo "CACHE_KEY=$CACHE_KEY"
          pnpm install --frozen-lockfile

      - uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            ~/.pnpm-cache
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Print cache size
        run: du -sh ~/.pnpm-store
        # Print the size of the pnpm store cache directory, so that you can keep track of the cache size and avoid exceeding GitHub's cache size limits
