name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.30.3

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Print cache size
        run: du -sh ~/.pnpm-store

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Print cache size
        run: du -sh ~/.pnpm-store
        # Print the size of the pnpm store cache directory, so that you can keep track of the cache size and avoid exceeding GitHub's cache size limits
